[package]
name = "lru_map"
version = "0.1.0"
authors = ["jasper <huangjasper@126.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arrayvec = "^0.7.0"